export enum ScreenNamesEnum {
    TabNavigator = "TabNavigator",
    
    User = "User",
    EditUser = "EditUser",
    Setting = "Setting",
    NotificationSetting = "NotificationSetting",
    Notification = "Notification",
    Home = "Home",
    Workout = "Workout",
    Nutrition = "Nutrition",
    Progress = "Progress",
    Introduce = "Introduce",
    Introduce2 = "Introduce2",
    Introduce3 = "Introduce3",
    Introduce4 = "Introduce4",
    Introduce5 = "Introduce5",
    Search = "Search",
    WorkoutDetail = "WorkoutDetail",
    WorkoutVideo = "WorkoutVideo",
    Routine = "Routine",
    CreateRoutine = "CreateRoutine",
    CreateNutrition = "CreateNutrition",
}